<?xml version="1.0" encoding="utf-8"?><Database Name="GlymaPermissions" Class="PermissionsDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHRIS-LAPTOP;Initial Catalog=GlymaPermissions;Integrated Security=True" SettingsObjectName="Glyma.Security.Properties.Settings" SettingsPropertyName="GlymaPermissionsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GroupAssociations" Member="GroupAssociations">
    <Type Name="GroupAssociation">
      <Column Name="GroupAssociationId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecurableParentUid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SecurableObjectUid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BreakInheritance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Group_GroupAssociation" Member="Group" ThisKey="GroupId" OtherKey="GroupId" Type="Group" IsForeignKey="true" />
      <Association Name="SecurableContext_GroupAssociation" Member="SecurableContext" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="SecurableContext" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Claim" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Membership" Member="Memberships" ThisKey="UserId" OtherKey="UserId" Type="Membership" />
      <Association Name="SecurableContext_User" Member="SecurableContext" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="SecurableContext" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_GroupAssociation" Member="GroupAssociations" ThisKey="GroupId" OtherKey="GroupId" Type="GroupAssociation" />
      <Association Name="Group_Membership" Member="Memberships" ThisKey="GroupId" OtherKey="GroupId" Type="Membership" />
      <Association Name="Role_Group" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Memberships" Member="Memberships">
    <Type Name="Membership">
      <Column Name="MembershipId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_Membership" Member="Group" ThisKey="GroupId" OtherKey="GroupId" Type="Group" IsForeignKey="true" />
      <Association Name="User_Membership" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="SecurableContext_Membership" Member="SecurableContext" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="SecurableContext" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RightAssociations" Member="RightAssociations">
    <Type Name="RightAssociation">
      <Column Name="RightAssociationId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RightId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Right_RightAssociation" Member="Right" ThisKey="RightId" OtherKey="RightId" Type="Right" IsForeignKey="true" />
      <Association Name="Role_RightAssociation" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="SecurableContext_RightAssociation" Member="SecurableContext" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="SecurableContext" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rights" Member="Rights">
    <Type Name="Right">
      <Column Name="RightId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Right_RightAssociation" Member="RightAssociations" ThisKey="RightId" OtherKey="RightId" Type="RightAssociation" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Role_Group" Member="Groups" ThisKey="RoleId" OtherKey="RoleId" Type="Group" />
      <Association Name="Role_RightAssociation" Member="RightAssociations" ThisKey="RoleId" OtherKey="RoleId" Type="RightAssociation" />
      <Association Name="SecurableContext_Role" Member="SecurableContext" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="SecurableContext" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SecurableContexts" Member="SecurableContexts">
    <Type Name="SecurableContext">
      <Column Name="SecurableContextId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SecurableContextName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurableContextUid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="SecurableContext_GroupAssociation" Member="GroupAssociations" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="GroupAssociation" />
      <Association Name="SecurableContext_User" Member="Users" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="User" />
      <Association Name="SecurableContext_Membership" Member="Memberships" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="Membership" />
      <Association Name="SecurableContext_RightAssociation" Member="RightAssociations" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="RightAssociation" />
      <Association Name="SecurableContext_Role" Member="Roles" ThisKey="SecurableContextId" OtherKey="SecurableContextId" Type="Role" />
    </Type>
  </Table>
</Database>