//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverlightMappingToolBasic.GlymaSecurityService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObject", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse))]
    public partial class ResponseObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private bool HasErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermissionLevelResponse", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GetPermissionLevelResponse : SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject {
        
        private SilverlightMappingToolBasic.GlymaSecurityService.GlymaPermissionLevel ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightMappingToolBasic.GlymaSecurityService.GlymaPermissionLevel Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllSecurityGroupsResponse", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GetAllSecurityGroupsResponse : SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject {
        
        private System.Collections.Generic.Dictionary<SilverlightMappingToolBasic.GlymaSecurityService.GlymaPermissionLevel, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup>> ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<SilverlightMappingToolBasic.GlymaSecurityService.GlymaPermissionLevel, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup>> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSecurableContextIdResponse", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GetSecurableContextIdResponse : SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject {
        
        private int ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSecurityAssociationsResponse", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GetSecurityAssociationsResponse : SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject {
        
        private SilverlightMappingToolBasic.GlymaSecurityService.SecurityAssociations ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightMappingToolBasic.GlymaSecurityService.SecurityAssociations Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermissionNameResponse", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GetPermissionNameResponse : SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject {
        
        private string ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlymaPermissionLevel", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public enum GlymaPermissionLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaSecurityManager = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaProjectManager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaMapManager = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaMapAuthor = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaMapReader = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaMapAuthorOld = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaMapReaderOld = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlymaSecurityGroup", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GlymaSecurityGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DisplayNameField;
        
        private int GroupIdField;
        
        private int SecurableContextIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurableContextId {
            get {
                return this.SecurableContextIdField;
            }
            set {
                if ((this.SecurableContextIdField.Equals(value) != true)) {
                    this.SecurableContextIdField = value;
                    this.RaisePropertyChanged("SecurableContextId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityAssociations", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class SecurityAssociations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup, bool> HasAssociationsField;
        
        private bool IsInheritedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup, bool> HasAssociations {
            get {
                return this.HasAssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.HasAssociationsField, value) != true)) {
                    this.HasAssociationsField = value;
                    this.RaisePropertyChanged("HasAssociations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInherited {
            get {
                return this.IsInheritedField;
            }
            set {
                if ((this.IsInheritedField.Equals(value) != true)) {
                    this.IsInheritedField = value;
                    this.RaisePropertyChanged("IsInherited");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlymaSecurityAssociation", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GlymaSecurityAssociation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool BreakInheritanceField;
        
        private SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup GlymaSecurityGroupField;
        
        private SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject SecurableObjectField;
        
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BreakInheritance {
            get {
                return this.BreakInheritanceField;
            }
            set {
                if ((this.BreakInheritanceField.Equals(value) != true)) {
                    this.BreakInheritanceField = value;
                    this.RaisePropertyChanged("BreakInheritance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup GlymaSecurityGroup {
            get {
                return this.GlymaSecurityGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GlymaSecurityGroupField, value) != true)) {
                    this.GlymaSecurityGroupField = value;
                    this.RaisePropertyChanged("GlymaSecurityGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject SecurableObject {
            get {
                return this.SecurableObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurableObjectField, value) != true)) {
                    this.SecurableObjectField = value;
                    this.RaisePropertyChanged("SecurableObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlymaSecurableObject", Namespace="http://schemas.datacontract.org/2004/07/Glyma.Security")]
    public partial class GlymaSecurableObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid SecurableObjectUidField;
        
        private System.Guid SecurableParentUidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SecurableObjectUid {
            get {
                return this.SecurableObjectUidField;
            }
            set {
                if ((this.SecurableObjectUidField.Equals(value) != true)) {
                    this.SecurableObjectUidField = value;
                    this.RaisePropertyChanged("SecurableObjectUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SecurableParentUid {
            get {
                return this.SecurableParentUidField;
            }
            set {
                if ((this.SecurableParentUidField.Equals(value) != true)) {
                    this.SecurableParentUidField = value;
                    this.RaisePropertyChanged("SecurableParentUid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sevensigma.com.au/GlymaSecurityService", ConfigurationName="GlymaSecurityService.IGlymaSecurityService")]
    public interface IGlymaSecurityService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetUsersPermi" +
            "ssionLevelName", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetUsersPermi" +
            "ssionLevelNameResponse")]
        System.IAsyncResult BeginGetUsersPermissionLevelName(string webUrl, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse EndGetUsersPermissionLevelName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetUsersPermi" +
            "ssionLevel", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetUsersPermi" +
            "ssionLevelResponse")]
        System.IAsyncResult BeginGetUsersPermissionLevel(string webUrl, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse EndGetUsersPermissionLevel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetAllSecurit" +
            "yGroups", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetAllSecurit" +
            "yGroupsResponse")]
        System.IAsyncResult BeginGetAllSecurityGroups(string webUrl, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse EndGetAllSecurityGroups(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetSecurableC" +
            "ontextId", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetSecurableC" +
            "ontextIdResponse")]
        System.IAsyncResult BeginGetSecurableContextId(string webUrl, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse EndGetSecurableContextId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/UpdateSecurit" +
            "yAssociations", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/UpdateSecurit" +
            "yAssociationsResponse")]
        System.IAsyncResult BeginUpdateSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndUpdateSecurityAssociations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetSecurityAs" +
            "sociations", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetSecurityAs" +
            "sociationsResponse")]
        System.IAsyncResult BeginGetSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse EndGetSecurityAssociations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetPermission" +
            "NameForObject", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetPermission" +
            "NameForObjectResponse")]
        System.IAsyncResult BeginGetPermissionNameForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse EndGetPermissionNameForObject(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetPermission" +
            "LevelForObject", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/GetPermission" +
            "LevelForObjectResponse")]
        System.IAsyncResult BeginGetPermissionLevelForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse EndGetPermissionLevelForObject(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/SetProjectMan" +
            "agerGroupAssociations", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/SetProjectMan" +
            "agerGroupAssociationsResponse")]
        System.IAsyncResult BeginSetProjectManagerGroupAssociations(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndSetProjectManagerGroupAssociations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/BreakRootMapI" +
            "nheritance", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/BreakRootMapI" +
            "nheritanceResponse")]
        System.IAsyncResult BeginBreakRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndBreakRootMapInheritance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/RestoreRootMa" +
            "pInheritance", ReplyAction="http://sevensigma.com.au/GlymaSecurityService/IGlymaSecurityService/RestoreRootMa" +
            "pInheritanceResponse")]
        System.IAsyncResult BeginRestoreRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState);
        
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse EndRestoreRootMapInheritance(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGlymaSecurityServiceChannel : SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUsersPermissionLevelNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersPermissionLevelNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUsersPermissionLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUsersPermissionLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllSecurityGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllSecurityGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSecurableContextIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSecurableContextIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateSecurityAssociationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateSecurityAssociationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSecurityAssociationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSecurityAssociationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPermissionNameForObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPermissionNameForObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPermissionLevelForObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPermissionLevelForObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetProjectManagerGroupAssociationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetProjectManagerGroupAssociationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BreakRootMapInheritanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BreakRootMapInheritanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestoreRootMapInheritanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RestoreRootMapInheritanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlymaSecurityServiceClient : System.ServiceModel.ClientBase<SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService>, SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService {
        
        private BeginOperationDelegate onBeginGetUsersPermissionLevelNameDelegate;
        
        private EndOperationDelegate onEndGetUsersPermissionLevelNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersPermissionLevelNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUsersPermissionLevelDelegate;
        
        private EndOperationDelegate onEndGetUsersPermissionLevelDelegate;
        
        private System.Threading.SendOrPostCallback onGetUsersPermissionLevelCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllSecurityGroupsDelegate;
        
        private EndOperationDelegate onEndGetAllSecurityGroupsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllSecurityGroupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSecurableContextIdDelegate;
        
        private EndOperationDelegate onEndGetSecurableContextIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetSecurableContextIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateSecurityAssociationsDelegate;
        
        private EndOperationDelegate onEndUpdateSecurityAssociationsDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateSecurityAssociationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSecurityAssociationsDelegate;
        
        private EndOperationDelegate onEndGetSecurityAssociationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetSecurityAssociationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPermissionNameForObjectDelegate;
        
        private EndOperationDelegate onEndGetPermissionNameForObjectDelegate;
        
        private System.Threading.SendOrPostCallback onGetPermissionNameForObjectCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPermissionLevelForObjectDelegate;
        
        private EndOperationDelegate onEndGetPermissionLevelForObjectDelegate;
        
        private System.Threading.SendOrPostCallback onGetPermissionLevelForObjectCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetProjectManagerGroupAssociationsDelegate;
        
        private EndOperationDelegate onEndSetProjectManagerGroupAssociationsDelegate;
        
        private System.Threading.SendOrPostCallback onSetProjectManagerGroupAssociationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginBreakRootMapInheritanceDelegate;
        
        private EndOperationDelegate onEndBreakRootMapInheritanceDelegate;
        
        private System.Threading.SendOrPostCallback onBreakRootMapInheritanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginRestoreRootMapInheritanceDelegate;
        
        private EndOperationDelegate onEndRestoreRootMapInheritanceDelegate;
        
        private System.Threading.SendOrPostCallback onRestoreRootMapInheritanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GlymaSecurityServiceClient() {
        }
        
        public GlymaSecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlymaSecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlymaSecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlymaSecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUsersPermissionLevelNameCompletedEventArgs> GetUsersPermissionLevelNameCompleted;
        
        public event System.EventHandler<GetUsersPermissionLevelCompletedEventArgs> GetUsersPermissionLevelCompleted;
        
        public event System.EventHandler<GetAllSecurityGroupsCompletedEventArgs> GetAllSecurityGroupsCompleted;
        
        public event System.EventHandler<GetSecurableContextIdCompletedEventArgs> GetSecurableContextIdCompleted;
        
        public event System.EventHandler<UpdateSecurityAssociationsCompletedEventArgs> UpdateSecurityAssociationsCompleted;
        
        public event System.EventHandler<GetSecurityAssociationsCompletedEventArgs> GetSecurityAssociationsCompleted;
        
        public event System.EventHandler<GetPermissionNameForObjectCompletedEventArgs> GetPermissionNameForObjectCompleted;
        
        public event System.EventHandler<GetPermissionLevelForObjectCompletedEventArgs> GetPermissionLevelForObjectCompleted;
        
        public event System.EventHandler<SetProjectManagerGroupAssociationsCompletedEventArgs> SetProjectManagerGroupAssociationsCompleted;
        
        public event System.EventHandler<BreakRootMapInheritanceCompletedEventArgs> BreakRootMapInheritanceCompleted;
        
        public event System.EventHandler<RestoreRootMapInheritanceCompletedEventArgs> RestoreRootMapInheritanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetUsersPermissionLevelName(string webUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsersPermissionLevelName(webUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetUsersPermissionLevelName(System.IAsyncResult result) {
            return base.Channel.EndGetUsersPermissionLevelName(result);
        }
        
        private System.IAsyncResult OnBeginGetUsersPermissionLevelName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetUsersPermissionLevelName(webUrl, callback, asyncState);
        }
        
        private object[] OnEndGetUsersPermissionLevelName(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetUsersPermissionLevelName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUsersPermissionLevelNameCompleted(object state) {
            if ((this.GetUsersPermissionLevelNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersPermissionLevelNameCompleted(this, new GetUsersPermissionLevelNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersPermissionLevelNameAsync(string webUrl) {
            this.GetUsersPermissionLevelNameAsync(webUrl, null);
        }
        
        public void GetUsersPermissionLevelNameAsync(string webUrl, object userState) {
            if ((this.onBeginGetUsersPermissionLevelNameDelegate == null)) {
                this.onBeginGetUsersPermissionLevelNameDelegate = new BeginOperationDelegate(this.OnBeginGetUsersPermissionLevelName);
            }
            if ((this.onEndGetUsersPermissionLevelNameDelegate == null)) {
                this.onEndGetUsersPermissionLevelNameDelegate = new EndOperationDelegate(this.OnEndGetUsersPermissionLevelName);
            }
            if ((this.onGetUsersPermissionLevelNameCompletedDelegate == null)) {
                this.onGetUsersPermissionLevelNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersPermissionLevelNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersPermissionLevelNameDelegate, new object[] {
                        webUrl}, this.onEndGetUsersPermissionLevelNameDelegate, this.onGetUsersPermissionLevelNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetUsersPermissionLevel(string webUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUsersPermissionLevel(webUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetUsersPermissionLevel(System.IAsyncResult result) {
            return base.Channel.EndGetUsersPermissionLevel(result);
        }
        
        private System.IAsyncResult OnBeginGetUsersPermissionLevel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetUsersPermissionLevel(webUrl, callback, asyncState);
        }
        
        private object[] OnEndGetUsersPermissionLevel(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetUsersPermissionLevel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUsersPermissionLevelCompleted(object state) {
            if ((this.GetUsersPermissionLevelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUsersPermissionLevelCompleted(this, new GetUsersPermissionLevelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUsersPermissionLevelAsync(string webUrl) {
            this.GetUsersPermissionLevelAsync(webUrl, null);
        }
        
        public void GetUsersPermissionLevelAsync(string webUrl, object userState) {
            if ((this.onBeginGetUsersPermissionLevelDelegate == null)) {
                this.onBeginGetUsersPermissionLevelDelegate = new BeginOperationDelegate(this.OnBeginGetUsersPermissionLevel);
            }
            if ((this.onEndGetUsersPermissionLevelDelegate == null)) {
                this.onEndGetUsersPermissionLevelDelegate = new EndOperationDelegate(this.OnEndGetUsersPermissionLevel);
            }
            if ((this.onGetUsersPermissionLevelCompletedDelegate == null)) {
                this.onGetUsersPermissionLevelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUsersPermissionLevelCompleted);
            }
            base.InvokeAsync(this.onBeginGetUsersPermissionLevelDelegate, new object[] {
                        webUrl}, this.onEndGetUsersPermissionLevelDelegate, this.onGetUsersPermissionLevelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetAllSecurityGroups(string webUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllSecurityGroups(webUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetAllSecurityGroups(System.IAsyncResult result) {
            return base.Channel.EndGetAllSecurityGroups(result);
        }
        
        private System.IAsyncResult OnBeginGetAllSecurityGroups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetAllSecurityGroups(webUrl, callback, asyncState);
        }
        
        private object[] OnEndGetAllSecurityGroups(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetAllSecurityGroups(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllSecurityGroupsCompleted(object state) {
            if ((this.GetAllSecurityGroupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllSecurityGroupsCompleted(this, new GetAllSecurityGroupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllSecurityGroupsAsync(string webUrl) {
            this.GetAllSecurityGroupsAsync(webUrl, null);
        }
        
        public void GetAllSecurityGroupsAsync(string webUrl, object userState) {
            if ((this.onBeginGetAllSecurityGroupsDelegate == null)) {
                this.onBeginGetAllSecurityGroupsDelegate = new BeginOperationDelegate(this.OnBeginGetAllSecurityGroups);
            }
            if ((this.onEndGetAllSecurityGroupsDelegate == null)) {
                this.onEndGetAllSecurityGroupsDelegate = new EndOperationDelegate(this.OnEndGetAllSecurityGroups);
            }
            if ((this.onGetAllSecurityGroupsCompletedDelegate == null)) {
                this.onGetAllSecurityGroupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllSecurityGroupsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllSecurityGroupsDelegate, new object[] {
                        webUrl}, this.onEndGetAllSecurityGroupsDelegate, this.onGetAllSecurityGroupsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetSecurableContextId(string webUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSecurableContextId(webUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetSecurableContextId(System.IAsyncResult result) {
            return base.Channel.EndGetSecurableContextId(result);
        }
        
        private System.IAsyncResult OnBeginGetSecurableContextId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetSecurableContextId(webUrl, callback, asyncState);
        }
        
        private object[] OnEndGetSecurableContextId(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetSecurableContextId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSecurableContextIdCompleted(object state) {
            if ((this.GetSecurableContextIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSecurableContextIdCompleted(this, new GetSecurableContextIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSecurableContextIdAsync(string webUrl) {
            this.GetSecurableContextIdAsync(webUrl, null);
        }
        
        public void GetSecurableContextIdAsync(string webUrl, object userState) {
            if ((this.onBeginGetSecurableContextIdDelegate == null)) {
                this.onBeginGetSecurableContextIdDelegate = new BeginOperationDelegate(this.OnBeginGetSecurableContextId);
            }
            if ((this.onEndGetSecurableContextIdDelegate == null)) {
                this.onEndGetSecurableContextIdDelegate = new EndOperationDelegate(this.OnEndGetSecurableContextId);
            }
            if ((this.onGetSecurableContextIdCompletedDelegate == null)) {
                this.onGetSecurableContextIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSecurableContextIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetSecurableContextIdDelegate, new object[] {
                        webUrl}, this.onEndGetSecurableContextIdDelegate, this.onGetSecurableContextIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginUpdateSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateSecurityAssociations(webUrl, securityAssocation, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndUpdateSecurityAssociations(System.IAsyncResult result) {
            return base.Channel.EndUpdateSecurityAssociations(result);
        }
        
        private System.IAsyncResult OnBeginUpdateSecurityAssociations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation = ((System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation>)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginUpdateSecurityAssociations(webUrl, securityAssocation, callback, asyncState);
        }
        
        private object[] OnEndUpdateSecurityAssociations(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndUpdateSecurityAssociations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateSecurityAssociationsCompleted(object state) {
            if ((this.UpdateSecurityAssociationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateSecurityAssociationsCompleted(this, new UpdateSecurityAssociationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateSecurityAssociationsAsync(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation) {
            this.UpdateSecurityAssociationsAsync(webUrl, securityAssocation, null);
        }
        
        public void UpdateSecurityAssociationsAsync(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation, object userState) {
            if ((this.onBeginUpdateSecurityAssociationsDelegate == null)) {
                this.onBeginUpdateSecurityAssociationsDelegate = new BeginOperationDelegate(this.OnBeginUpdateSecurityAssociations);
            }
            if ((this.onEndUpdateSecurityAssociationsDelegate == null)) {
                this.onEndUpdateSecurityAssociationsDelegate = new EndOperationDelegate(this.OnEndUpdateSecurityAssociations);
            }
            if ((this.onUpdateSecurityAssociationsCompletedDelegate == null)) {
                this.onUpdateSecurityAssociationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateSecurityAssociationsCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateSecurityAssociationsDelegate, new object[] {
                        webUrl,
                        securityAssocation}, this.onEndUpdateSecurityAssociationsDelegate, this.onUpdateSecurityAssociationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSecurityAssociations(webUrl, groups, securbleObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetSecurityAssociations(System.IAsyncResult result) {
            return base.Channel.EndGetSecurityAssociations(result);
        }
        
        private System.IAsyncResult OnBeginGetSecurityAssociations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups = ((System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup>)(inValues[1]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[2]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetSecurityAssociations(webUrl, groups, securbleObject, callback, asyncState);
        }
        
        private object[] OnEndGetSecurityAssociations(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetSecurityAssociations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSecurityAssociationsCompleted(object state) {
            if ((this.GetSecurityAssociationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSecurityAssociationsCompleted(this, new GetSecurityAssociationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSecurityAssociationsAsync(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject) {
            this.GetSecurityAssociationsAsync(webUrl, groups, securbleObject, null);
        }
        
        public void GetSecurityAssociationsAsync(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, object userState) {
            if ((this.onBeginGetSecurityAssociationsDelegate == null)) {
                this.onBeginGetSecurityAssociationsDelegate = new BeginOperationDelegate(this.OnBeginGetSecurityAssociations);
            }
            if ((this.onEndGetSecurityAssociationsDelegate == null)) {
                this.onEndGetSecurityAssociationsDelegate = new EndOperationDelegate(this.OnEndGetSecurityAssociations);
            }
            if ((this.onGetSecurityAssociationsCompletedDelegate == null)) {
                this.onGetSecurityAssociationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSecurityAssociationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetSecurityAssociationsDelegate, new object[] {
                        webUrl,
                        groups,
                        securbleObject}, this.onEndGetSecurityAssociationsDelegate, this.onGetSecurityAssociationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetPermissionNameForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPermissionNameForObject(webUrl, securbleObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetPermissionNameForObject(System.IAsyncResult result) {
            return base.Channel.EndGetPermissionNameForObject(result);
        }
        
        private System.IAsyncResult OnBeginGetPermissionNameForObject(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetPermissionNameForObject(webUrl, securbleObject, callback, asyncState);
        }
        
        private object[] OnEndGetPermissionNameForObject(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetPermissionNameForObject(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPermissionNameForObjectCompleted(object state) {
            if ((this.GetPermissionNameForObjectCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPermissionNameForObjectCompleted(this, new GetPermissionNameForObjectCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPermissionNameForObjectAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject) {
            this.GetPermissionNameForObjectAsync(webUrl, securbleObject, null);
        }
        
        public void GetPermissionNameForObjectAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, object userState) {
            if ((this.onBeginGetPermissionNameForObjectDelegate == null)) {
                this.onBeginGetPermissionNameForObjectDelegate = new BeginOperationDelegate(this.OnBeginGetPermissionNameForObject);
            }
            if ((this.onEndGetPermissionNameForObjectDelegate == null)) {
                this.onEndGetPermissionNameForObjectDelegate = new EndOperationDelegate(this.OnEndGetPermissionNameForObject);
            }
            if ((this.onGetPermissionNameForObjectCompletedDelegate == null)) {
                this.onGetPermissionNameForObjectCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPermissionNameForObjectCompleted);
            }
            base.InvokeAsync(this.onBeginGetPermissionNameForObjectDelegate, new object[] {
                        webUrl,
                        securbleObject}, this.onEndGetPermissionNameForObjectDelegate, this.onGetPermissionNameForObjectCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginGetPermissionLevelForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPermissionLevelForObject(webUrl, securbleObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndGetPermissionLevelForObject(System.IAsyncResult result) {
            return base.Channel.EndGetPermissionLevelForObject(result);
        }
        
        private System.IAsyncResult OnBeginGetPermissionLevelForObject(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginGetPermissionLevelForObject(webUrl, securbleObject, callback, asyncState);
        }
        
        private object[] OnEndGetPermissionLevelForObject(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndGetPermissionLevelForObject(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPermissionLevelForObjectCompleted(object state) {
            if ((this.GetPermissionLevelForObjectCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPermissionLevelForObjectCompleted(this, new GetPermissionLevelForObjectCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPermissionLevelForObjectAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject) {
            this.GetPermissionLevelForObjectAsync(webUrl, securbleObject, null);
        }
        
        public void GetPermissionLevelForObjectAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, object userState) {
            if ((this.onBeginGetPermissionLevelForObjectDelegate == null)) {
                this.onBeginGetPermissionLevelForObjectDelegate = new BeginOperationDelegate(this.OnBeginGetPermissionLevelForObject);
            }
            if ((this.onEndGetPermissionLevelForObjectDelegate == null)) {
                this.onEndGetPermissionLevelForObjectDelegate = new EndOperationDelegate(this.OnEndGetPermissionLevelForObject);
            }
            if ((this.onGetPermissionLevelForObjectCompletedDelegate == null)) {
                this.onGetPermissionLevelForObjectCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPermissionLevelForObjectCompleted);
            }
            base.InvokeAsync(this.onBeginGetPermissionLevelForObjectDelegate, new object[] {
                        webUrl,
                        securbleObject}, this.onEndGetPermissionLevelForObjectDelegate, this.onGetPermissionLevelForObjectCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginSetProjectManagerGroupAssociations(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetProjectManagerGroupAssociations(webUrl, securableObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndSetProjectManagerGroupAssociations(System.IAsyncResult result) {
            return base.Channel.EndSetProjectManagerGroupAssociations(result);
        }
        
        private System.IAsyncResult OnBeginSetProjectManagerGroupAssociations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginSetProjectManagerGroupAssociations(webUrl, securableObject, callback, asyncState);
        }
        
        private object[] OnEndSetProjectManagerGroupAssociations(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndSetProjectManagerGroupAssociations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetProjectManagerGroupAssociationsCompleted(object state) {
            if ((this.SetProjectManagerGroupAssociationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetProjectManagerGroupAssociationsCompleted(this, new SetProjectManagerGroupAssociationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetProjectManagerGroupAssociationsAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject) {
            this.SetProjectManagerGroupAssociationsAsync(webUrl, securableObject, null);
        }
        
        public void SetProjectManagerGroupAssociationsAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, object userState) {
            if ((this.onBeginSetProjectManagerGroupAssociationsDelegate == null)) {
                this.onBeginSetProjectManagerGroupAssociationsDelegate = new BeginOperationDelegate(this.OnBeginSetProjectManagerGroupAssociations);
            }
            if ((this.onEndSetProjectManagerGroupAssociationsDelegate == null)) {
                this.onEndSetProjectManagerGroupAssociationsDelegate = new EndOperationDelegate(this.OnEndSetProjectManagerGroupAssociations);
            }
            if ((this.onSetProjectManagerGroupAssociationsCompletedDelegate == null)) {
                this.onSetProjectManagerGroupAssociationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetProjectManagerGroupAssociationsCompleted);
            }
            base.InvokeAsync(this.onBeginSetProjectManagerGroupAssociationsDelegate, new object[] {
                        webUrl,
                        securableObject}, this.onEndSetProjectManagerGroupAssociationsDelegate, this.onSetProjectManagerGroupAssociationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginBreakRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBreakRootMapInheritance(webUrl, securableObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndBreakRootMapInheritance(System.IAsyncResult result) {
            return base.Channel.EndBreakRootMapInheritance(result);
        }
        
        private System.IAsyncResult OnBeginBreakRootMapInheritance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginBreakRootMapInheritance(webUrl, securableObject, callback, asyncState);
        }
        
        private object[] OnEndBreakRootMapInheritance(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndBreakRootMapInheritance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBreakRootMapInheritanceCompleted(object state) {
            if ((this.BreakRootMapInheritanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BreakRootMapInheritanceCompleted(this, new BreakRootMapInheritanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BreakRootMapInheritanceAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject) {
            this.BreakRootMapInheritanceAsync(webUrl, securableObject, null);
        }
        
        public void BreakRootMapInheritanceAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, object userState) {
            if ((this.onBeginBreakRootMapInheritanceDelegate == null)) {
                this.onBeginBreakRootMapInheritanceDelegate = new BeginOperationDelegate(this.OnBeginBreakRootMapInheritance);
            }
            if ((this.onEndBreakRootMapInheritanceDelegate == null)) {
                this.onEndBreakRootMapInheritanceDelegate = new EndOperationDelegate(this.OnEndBreakRootMapInheritance);
            }
            if ((this.onBreakRootMapInheritanceCompletedDelegate == null)) {
                this.onBreakRootMapInheritanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBreakRootMapInheritanceCompleted);
            }
            base.InvokeAsync(this.onBeginBreakRootMapInheritanceDelegate, new object[] {
                        webUrl,
                        securableObject}, this.onEndBreakRootMapInheritanceDelegate, this.onBreakRootMapInheritanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.BeginRestoreRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRestoreRootMapInheritance(webUrl, securableObject, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService.EndRestoreRootMapInheritance(System.IAsyncResult result) {
            return base.Channel.EndRestoreRootMapInheritance(result);
        }
        
        private System.IAsyncResult OnBeginRestoreRootMapInheritance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string webUrl = ((string)(inValues[0]));
            SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject = ((SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject)(inValues[1]));
            return ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).BeginRestoreRootMapInheritance(webUrl, securableObject, callback, asyncState);
        }
        
        private object[] OnEndRestoreRootMapInheritance(System.IAsyncResult result) {
            SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse retVal = ((SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService)(this)).EndRestoreRootMapInheritance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRestoreRootMapInheritanceCompleted(object state) {
            if ((this.RestoreRootMapInheritanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RestoreRootMapInheritanceCompleted(this, new RestoreRootMapInheritanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RestoreRootMapInheritanceAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject) {
            this.RestoreRootMapInheritanceAsync(webUrl, securableObject, null);
        }
        
        public void RestoreRootMapInheritanceAsync(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, object userState) {
            if ((this.onBeginRestoreRootMapInheritanceDelegate == null)) {
                this.onBeginRestoreRootMapInheritanceDelegate = new BeginOperationDelegate(this.OnBeginRestoreRootMapInheritance);
            }
            if ((this.onEndRestoreRootMapInheritanceDelegate == null)) {
                this.onEndRestoreRootMapInheritanceDelegate = new EndOperationDelegate(this.OnEndRestoreRootMapInheritance);
            }
            if ((this.onRestoreRootMapInheritanceCompletedDelegate == null)) {
                this.onRestoreRootMapInheritanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRestoreRootMapInheritanceCompleted);
            }
            base.InvokeAsync(this.onBeginRestoreRootMapInheritanceDelegate, new object[] {
                        webUrl,
                        securableObject}, this.onEndRestoreRootMapInheritanceDelegate, this.onRestoreRootMapInheritanceCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService CreateChannel() {
            return new GlymaSecurityServiceClientChannel(this);
        }
        
        private class GlymaSecurityServiceClientChannel : ChannelBase<SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService>, SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService {
            
            public GlymaSecurityServiceClientChannel(System.ServiceModel.ClientBase<SilverlightMappingToolBasic.GlymaSecurityService.IGlymaSecurityService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUsersPermissionLevelName(string webUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = webUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetUsersPermissionLevelName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse EndGetUsersPermissionLevelName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse)(base.EndInvoke("GetUsersPermissionLevelName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUsersPermissionLevel(string webUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = webUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetUsersPermissionLevel", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse EndGetUsersPermissionLevel(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse)(base.EndInvoke("GetUsersPermissionLevel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllSecurityGroups(string webUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = webUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetAllSecurityGroups", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse EndGetAllSecurityGroups(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetAllSecurityGroupsResponse)(base.EndInvoke("GetAllSecurityGroups", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSecurableContextId(string webUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = webUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetSecurableContextId", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse EndGetSecurableContextId(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurableContextIdResponse)(base.EndInvoke("GetSecurableContextId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityAssociation> securityAssocation, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securityAssocation;
                System.IAsyncResult _result = base.BeginInvoke("UpdateSecurityAssociations", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndUpdateSecurityAssociations(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject _result = ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(base.EndInvoke("UpdateSecurityAssociations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSecurityAssociations(string webUrl, System.Collections.ObjectModel.ObservableCollection<SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurityGroup> groups, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = webUrl;
                _args[1] = groups;
                _args[2] = securbleObject;
                System.IAsyncResult _result = base.BeginInvoke("GetSecurityAssociations", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse EndGetSecurityAssociations(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse)(base.EndInvoke("GetSecurityAssociations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPermissionNameForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securbleObject;
                System.IAsyncResult _result = base.BeginInvoke("GetPermissionNameForObject", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse EndGetPermissionNameForObject(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionNameResponse)(base.EndInvoke("GetPermissionNameForObject", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPermissionLevelForObject(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securbleObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securbleObject;
                System.IAsyncResult _result = base.BeginInvoke("GetPermissionLevelForObject", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse EndGetPermissionLevelForObject(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetPermissionLevelResponse)(base.EndInvoke("GetPermissionLevelForObject", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetProjectManagerGroupAssociations(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securableObject;
                System.IAsyncResult _result = base.BeginInvoke("SetProjectManagerGroupAssociations", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndSetProjectManagerGroupAssociations(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject _result = ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(base.EndInvoke("SetProjectManagerGroupAssociations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBreakRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securableObject;
                System.IAsyncResult _result = base.BeginInvoke("BreakRootMapInheritance", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject EndBreakRootMapInheritance(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject _result = ((SilverlightMappingToolBasic.GlymaSecurityService.ResponseObject)(base.EndInvoke("BreakRootMapInheritance", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRestoreRootMapInheritance(string webUrl, SilverlightMappingToolBasic.GlymaSecurityService.GlymaSecurableObject securableObject, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = webUrl;
                _args[1] = securableObject;
                System.IAsyncResult _result = base.BeginInvoke("RestoreRootMapInheritance", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse EndRestoreRootMapInheritance(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse _result = ((SilverlightMappingToolBasic.GlymaSecurityService.GetSecurityAssociationsResponse)(base.EndInvoke("RestoreRootMapInheritance", _args, result)));
                return _result;
            }
        }
    }
}
