//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Glyma.UtilityService.Proxy.Service {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportJobsResponse", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public partial class ExportJobsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<System.Guid, Glyma.UtilityService.Proxy.Service.ExportJob> ExportJobsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<System.Guid, Glyma.UtilityService.Proxy.Service.ExportJob> ExportJobs {
            get {
                return this.ExportJobsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportJobsField, value) != true)) {
                    this.ExportJobsField = value;
                    this.RaisePropertyChanged("ExportJobs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportJob", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public partial class ExportJob : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> CreatedField;
        
        private Glyma.UtilityService.Proxy.Service.GlymaUser CreatedByField;
        
        private System.Collections.Generic.Dictionary<string, string> ExportPropertiesField;
        
        private System.Guid IdField;
        
        private bool IsCurrentField;
        
        private string LinkField;
        
        private Glyma.UtilityService.Proxy.Service.MapType MapTypeField;
        
        private int PercentageCompleteField;
        
        private System.Collections.ObjectModel.ObservableCollection<System.Guid> SelectedNodesField;
        
        private Glyma.UtilityService.Proxy.Service.ExportStatus StatusField;
        
        private Glyma.UtilityService.Proxy.Service.ExportType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glyma.UtilityService.Proxy.Service.GlymaUser CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExportProperties {
            get {
                return this.ExportPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportPropertiesField, value) != true)) {
                    this.ExportPropertiesField = value;
                    this.RaisePropertyChanged("ExportProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glyma.UtilityService.Proxy.Service.MapType MapType {
            get {
                return this.MapTypeField;
            }
            set {
                if ((this.MapTypeField.Equals(value) != true)) {
                    this.MapTypeField = value;
                    this.RaisePropertyChanged("MapType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PercentageComplete {
            get {
                return this.PercentageCompleteField;
            }
            set {
                if ((this.PercentageCompleteField.Equals(value) != true)) {
                    this.PercentageCompleteField = value;
                    this.RaisePropertyChanged("PercentageComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<System.Guid> SelectedNodes {
            get {
                return this.SelectedNodesField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedNodesField, value) != true)) {
                    this.SelectedNodesField = value;
                    this.RaisePropertyChanged("SelectedNodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glyma.UtilityService.Proxy.Service.ExportStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glyma.UtilityService.Proxy.Service.ExportType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
    public partial class ExportError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlymaUser", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public partial class GlymaUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DisplayNameField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapType", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public enum MapType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IBIS = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportStatus", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public enum ExportStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scheduled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportType", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public enum ExportType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Compendium = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Word = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlymaXml = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportJobResponse", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public partial class ExportJobResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Glyma.UtilityService.Proxy.Service.ExportJob ExportJobField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Glyma.UtilityService.Proxy.Service.ExportJob ExportJob {
            get {
                return this.ExportJobField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportJobField, value) != true)) {
                    this.ExportJobField = value;
                    this.RaisePropertyChanged("ExportJob");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportAvailabilityResponse", Namespace="http://sevensigma.com.au/GlymaUtilityService/ExportObjects")]
    public partial class ExportAvailabilityResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sevensigma.com.au/GlymaUtilityService", ConfigurationName="Service.IUtilityServiceManager")]
    public interface IUtilityServiceManager {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "", ReplyAction="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Glyma.UtilityService.Proxy.Service.ExportError), Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "ExportErrorFault", Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
        System.IAsyncResult BeginGetExportJobs(System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState);
        
        Glyma.UtilityService.Proxy.Service.ExportJobsResponse EndGetExportJobs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "ForMapType", ReplyAction="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "ForMapTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Glyma.UtilityService.Proxy.Service.ExportError), Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/GetExportJobs" +
            "ForMapTypeExportErrorFault", Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
        System.IAsyncResult BeginGetExportJobsForMapType(Glyma.UtilityService.Proxy.Service.MapType mapType, System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState);
        
        Glyma.UtilityService.Proxy.Service.ExportJobsResponse EndGetExportJobsForMapType(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/CreateExportJ" +
            "ob", ReplyAction="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/CreateExportJ" +
            "obResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Glyma.UtilityService.Proxy.Service.ExportError), Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/CreateExportJ" +
            "obExportErrorFault", Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
        System.IAsyncResult BeginCreateExportJob(System.Guid domainUid, System.Guid rootMapUid, System.Collections.Generic.Dictionary<string, string> exportProperties, Glyma.UtilityService.Proxy.Service.MapType mapType, Glyma.UtilityService.Proxy.Service.ExportType exportType, System.AsyncCallback callback, object asyncState);
        
        Glyma.UtilityService.Proxy.Service.ExportJobResponse EndCreateExportJob(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/DeleteExportJ" +
            "ob", ReplyAction="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/DeleteExportJ" +
            "obResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Glyma.UtilityService.Proxy.Service.ExportError), Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/DeleteExportJ" +
            "obExportErrorFault", Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
        System.IAsyncResult BeginDeleteExportJob(Glyma.UtilityService.Proxy.Service.ExportJob exportJob, System.AsyncCallback callback, object asyncState);
        
        Glyma.UtilityService.Proxy.Service.ExportJobResponse EndDeleteExportJob(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/IsExportingAv" +
            "ailable", ReplyAction="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/IsExportingAv" +
            "ailableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Glyma.UtilityService.Proxy.Service.ExportError), Action="http://sevensigma.com.au/GlymaUtilityService/IUtilityServiceManager/IsExportingAv" +
            "ailableExportErrorFault", Name="ExportError", Namespace="http://schemas.datacontract.org/2004/07/Glyma.UtilityService.Common")]
        System.IAsyncResult BeginIsExportingAvailable(System.AsyncCallback callback, object asyncState);
        
        Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse EndIsExportingAvailable(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilityServiceManagerChannel : Glyma.UtilityService.Proxy.Service.IUtilityServiceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetExportJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetExportJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Glyma.UtilityService.Proxy.Service.ExportJobsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Glyma.UtilityService.Proxy.Service.ExportJobsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetExportJobsForMapTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetExportJobsForMapTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Glyma.UtilityService.Proxy.Service.ExportJobsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Glyma.UtilityService.Proxy.Service.ExportJobsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateExportJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateExportJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Glyma.UtilityService.Proxy.Service.ExportJobResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Glyma.UtilityService.Proxy.Service.ExportJobResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteExportJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteExportJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Glyma.UtilityService.Proxy.Service.ExportJobResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Glyma.UtilityService.Proxy.Service.ExportJobResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsExportingAvailableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsExportingAvailableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityServiceManagerClient : System.ServiceModel.ClientBase<Glyma.UtilityService.Proxy.Service.IUtilityServiceManager>, Glyma.UtilityService.Proxy.Service.IUtilityServiceManager {
        
        private BeginOperationDelegate onBeginGetExportJobsDelegate;
        
        private EndOperationDelegate onEndGetExportJobsDelegate;
        
        private System.Threading.SendOrPostCallback onGetExportJobsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetExportJobsForMapTypeDelegate;
        
        private EndOperationDelegate onEndGetExportJobsForMapTypeDelegate;
        
        private System.Threading.SendOrPostCallback onGetExportJobsForMapTypeCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateExportJobDelegate;
        
        private EndOperationDelegate onEndCreateExportJobDelegate;
        
        private System.Threading.SendOrPostCallback onCreateExportJobCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteExportJobDelegate;
        
        private EndOperationDelegate onEndDeleteExportJobDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteExportJobCompletedDelegate;
        
        private BeginOperationDelegate onBeginIsExportingAvailableDelegate;
        
        private EndOperationDelegate onEndIsExportingAvailableDelegate;
        
        private System.Threading.SendOrPostCallback onIsExportingAvailableCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UtilityServiceManagerClient() {
        }
        
        public UtilityServiceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityServiceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityServiceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetExportJobsCompletedEventArgs> GetExportJobsCompleted;
        
        public event System.EventHandler<GetExportJobsForMapTypeCompletedEventArgs> GetExportJobsForMapTypeCompleted;
        
        public event System.EventHandler<CreateExportJobCompletedEventArgs> CreateExportJobCompleted;
        
        public event System.EventHandler<DeleteExportJobCompletedEventArgs> DeleteExportJobCompleted;
        
        public event System.EventHandler<IsExportingAvailableCompletedEventArgs> IsExportingAvailableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.BeginGetExportJobs(System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetExportJobs(domainUid, rootMapUid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glyma.UtilityService.Proxy.Service.ExportJobsResponse Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.EndGetExportJobs(System.IAsyncResult result) {
            return base.Channel.EndGetExportJobs(result);
        }
        
        private System.IAsyncResult OnBeginGetExportJobs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid domainUid = ((System.Guid)(inValues[0]));
            System.Guid rootMapUid = ((System.Guid)(inValues[1]));
            return ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).BeginGetExportJobs(domainUid, rootMapUid, callback, asyncState);
        }
        
        private object[] OnEndGetExportJobs(System.IAsyncResult result) {
            Glyma.UtilityService.Proxy.Service.ExportJobsResponse retVal = ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).EndGetExportJobs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetExportJobsCompleted(object state) {
            if ((this.GetExportJobsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetExportJobsCompleted(this, new GetExportJobsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetExportJobsAsync(System.Guid domainUid, System.Guid rootMapUid) {
            this.GetExportJobsAsync(domainUid, rootMapUid, null);
        }
        
        public void GetExportJobsAsync(System.Guid domainUid, System.Guid rootMapUid, object userState) {
            if ((this.onBeginGetExportJobsDelegate == null)) {
                this.onBeginGetExportJobsDelegate = new BeginOperationDelegate(this.OnBeginGetExportJobs);
            }
            if ((this.onEndGetExportJobsDelegate == null)) {
                this.onEndGetExportJobsDelegate = new EndOperationDelegate(this.OnEndGetExportJobs);
            }
            if ((this.onGetExportJobsCompletedDelegate == null)) {
                this.onGetExportJobsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetExportJobsCompleted);
            }
            base.InvokeAsync(this.onBeginGetExportJobsDelegate, new object[] {
                        domainUid,
                        rootMapUid}, this.onEndGetExportJobsDelegate, this.onGetExportJobsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.BeginGetExportJobsForMapType(Glyma.UtilityService.Proxy.Service.MapType mapType, System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetExportJobsForMapType(mapType, domainUid, rootMapUid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glyma.UtilityService.Proxy.Service.ExportJobsResponse Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.EndGetExportJobsForMapType(System.IAsyncResult result) {
            return base.Channel.EndGetExportJobsForMapType(result);
        }
        
        private System.IAsyncResult OnBeginGetExportJobsForMapType(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Glyma.UtilityService.Proxy.Service.MapType mapType = ((Glyma.UtilityService.Proxy.Service.MapType)(inValues[0]));
            System.Guid domainUid = ((System.Guid)(inValues[1]));
            System.Guid rootMapUid = ((System.Guid)(inValues[2]));
            return ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).BeginGetExportJobsForMapType(mapType, domainUid, rootMapUid, callback, asyncState);
        }
        
        private object[] OnEndGetExportJobsForMapType(System.IAsyncResult result) {
            Glyma.UtilityService.Proxy.Service.ExportJobsResponse retVal = ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).EndGetExportJobsForMapType(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetExportJobsForMapTypeCompleted(object state) {
            if ((this.GetExportJobsForMapTypeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetExportJobsForMapTypeCompleted(this, new GetExportJobsForMapTypeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetExportJobsForMapTypeAsync(Glyma.UtilityService.Proxy.Service.MapType mapType, System.Guid domainUid, System.Guid rootMapUid) {
            this.GetExportJobsForMapTypeAsync(mapType, domainUid, rootMapUid, null);
        }
        
        public void GetExportJobsForMapTypeAsync(Glyma.UtilityService.Proxy.Service.MapType mapType, System.Guid domainUid, System.Guid rootMapUid, object userState) {
            if ((this.onBeginGetExportJobsForMapTypeDelegate == null)) {
                this.onBeginGetExportJobsForMapTypeDelegate = new BeginOperationDelegate(this.OnBeginGetExportJobsForMapType);
            }
            if ((this.onEndGetExportJobsForMapTypeDelegate == null)) {
                this.onEndGetExportJobsForMapTypeDelegate = new EndOperationDelegate(this.OnEndGetExportJobsForMapType);
            }
            if ((this.onGetExportJobsForMapTypeCompletedDelegate == null)) {
                this.onGetExportJobsForMapTypeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetExportJobsForMapTypeCompleted);
            }
            base.InvokeAsync(this.onBeginGetExportJobsForMapTypeDelegate, new object[] {
                        mapType,
                        domainUid,
                        rootMapUid}, this.onEndGetExportJobsForMapTypeDelegate, this.onGetExportJobsForMapTypeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.BeginCreateExportJob(System.Guid domainUid, System.Guid rootMapUid, System.Collections.Generic.Dictionary<string, string> exportProperties, Glyma.UtilityService.Proxy.Service.MapType mapType, Glyma.UtilityService.Proxy.Service.ExportType exportType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateExportJob(domainUid, rootMapUid, exportProperties, mapType, exportType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glyma.UtilityService.Proxy.Service.ExportJobResponse Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.EndCreateExportJob(System.IAsyncResult result) {
            return base.Channel.EndCreateExportJob(result);
        }
        
        private System.IAsyncResult OnBeginCreateExportJob(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid domainUid = ((System.Guid)(inValues[0]));
            System.Guid rootMapUid = ((System.Guid)(inValues[1]));
            System.Collections.Generic.Dictionary<string, string> exportProperties = ((System.Collections.Generic.Dictionary<string, string>)(inValues[2]));
            Glyma.UtilityService.Proxy.Service.MapType mapType = ((Glyma.UtilityService.Proxy.Service.MapType)(inValues[3]));
            Glyma.UtilityService.Proxy.Service.ExportType exportType = ((Glyma.UtilityService.Proxy.Service.ExportType)(inValues[4]));
            return ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).BeginCreateExportJob(domainUid, rootMapUid, exportProperties, mapType, exportType, callback, asyncState);
        }
        
        private object[] OnEndCreateExportJob(System.IAsyncResult result) {
            Glyma.UtilityService.Proxy.Service.ExportJobResponse retVal = ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).EndCreateExportJob(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateExportJobCompleted(object state) {
            if ((this.CreateExportJobCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateExportJobCompleted(this, new CreateExportJobCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateExportJobAsync(System.Guid domainUid, System.Guid rootMapUid, System.Collections.Generic.Dictionary<string, string> exportProperties, Glyma.UtilityService.Proxy.Service.MapType mapType, Glyma.UtilityService.Proxy.Service.ExportType exportType) {
            this.CreateExportJobAsync(domainUid, rootMapUid, exportProperties, mapType, exportType, null);
        }
        
        public void CreateExportJobAsync(System.Guid domainUid, System.Guid rootMapUid, System.Collections.Generic.Dictionary<string, string> exportProperties, Glyma.UtilityService.Proxy.Service.MapType mapType, Glyma.UtilityService.Proxy.Service.ExportType exportType, object userState) {
            if ((this.onBeginCreateExportJobDelegate == null)) {
                this.onBeginCreateExportJobDelegate = new BeginOperationDelegate(this.OnBeginCreateExportJob);
            }
            if ((this.onEndCreateExportJobDelegate == null)) {
                this.onEndCreateExportJobDelegate = new EndOperationDelegate(this.OnEndCreateExportJob);
            }
            if ((this.onCreateExportJobCompletedDelegate == null)) {
                this.onCreateExportJobCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateExportJobCompleted);
            }
            base.InvokeAsync(this.onBeginCreateExportJobDelegate, new object[] {
                        domainUid,
                        rootMapUid,
                        exportProperties,
                        mapType,
                        exportType}, this.onEndCreateExportJobDelegate, this.onCreateExportJobCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.BeginDeleteExportJob(Glyma.UtilityService.Proxy.Service.ExportJob exportJob, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteExportJob(exportJob, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glyma.UtilityService.Proxy.Service.ExportJobResponse Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.EndDeleteExportJob(System.IAsyncResult result) {
            return base.Channel.EndDeleteExportJob(result);
        }
        
        private System.IAsyncResult OnBeginDeleteExportJob(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Glyma.UtilityService.Proxy.Service.ExportJob exportJob = ((Glyma.UtilityService.Proxy.Service.ExportJob)(inValues[0]));
            return ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).BeginDeleteExportJob(exportJob, callback, asyncState);
        }
        
        private object[] OnEndDeleteExportJob(System.IAsyncResult result) {
            Glyma.UtilityService.Proxy.Service.ExportJobResponse retVal = ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).EndDeleteExportJob(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteExportJobCompleted(object state) {
            if ((this.DeleteExportJobCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteExportJobCompleted(this, new DeleteExportJobCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteExportJobAsync(Glyma.UtilityService.Proxy.Service.ExportJob exportJob) {
            this.DeleteExportJobAsync(exportJob, null);
        }
        
        public void DeleteExportJobAsync(Glyma.UtilityService.Proxy.Service.ExportJob exportJob, object userState) {
            if ((this.onBeginDeleteExportJobDelegate == null)) {
                this.onBeginDeleteExportJobDelegate = new BeginOperationDelegate(this.OnBeginDeleteExportJob);
            }
            if ((this.onEndDeleteExportJobDelegate == null)) {
                this.onEndDeleteExportJobDelegate = new EndOperationDelegate(this.OnEndDeleteExportJob);
            }
            if ((this.onDeleteExportJobCompletedDelegate == null)) {
                this.onDeleteExportJobCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteExportJobCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteExportJobDelegate, new object[] {
                        exportJob}, this.onEndDeleteExportJobDelegate, this.onDeleteExportJobCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.BeginIsExportingAvailable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsExportingAvailable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse Glyma.UtilityService.Proxy.Service.IUtilityServiceManager.EndIsExportingAvailable(System.IAsyncResult result) {
            return base.Channel.EndIsExportingAvailable(result);
        }
        
        private System.IAsyncResult OnBeginIsExportingAvailable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).BeginIsExportingAvailable(callback, asyncState);
        }
        
        private object[] OnEndIsExportingAvailable(System.IAsyncResult result) {
            Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse retVal = ((Glyma.UtilityService.Proxy.Service.IUtilityServiceManager)(this)).EndIsExportingAvailable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsExportingAvailableCompleted(object state) {
            if ((this.IsExportingAvailableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsExportingAvailableCompleted(this, new IsExportingAvailableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsExportingAvailableAsync() {
            this.IsExportingAvailableAsync(null);
        }
        
        public void IsExportingAvailableAsync(object userState) {
            if ((this.onBeginIsExportingAvailableDelegate == null)) {
                this.onBeginIsExportingAvailableDelegate = new BeginOperationDelegate(this.OnBeginIsExportingAvailable);
            }
            if ((this.onEndIsExportingAvailableDelegate == null)) {
                this.onEndIsExportingAvailableDelegate = new EndOperationDelegate(this.OnEndIsExportingAvailable);
            }
            if ((this.onIsExportingAvailableCompletedDelegate == null)) {
                this.onIsExportingAvailableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsExportingAvailableCompleted);
            }
            base.InvokeAsync(this.onBeginIsExportingAvailableDelegate, null, this.onEndIsExportingAvailableDelegate, this.onIsExportingAvailableCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Glyma.UtilityService.Proxy.Service.IUtilityServiceManager CreateChannel() {
            return new UtilityServiceManagerClientChannel(this);
        }
        
        private class UtilityServiceManagerClientChannel : ChannelBase<Glyma.UtilityService.Proxy.Service.IUtilityServiceManager>, Glyma.UtilityService.Proxy.Service.IUtilityServiceManager {
            
            public UtilityServiceManagerClientChannel(System.ServiceModel.ClientBase<Glyma.UtilityService.Proxy.Service.IUtilityServiceManager> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetExportJobs(System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = domainUid;
                _args[1] = rootMapUid;
                System.IAsyncResult _result = base.BeginInvoke("GetExportJobs", _args, callback, asyncState);
                return _result;
            }
            
            public Glyma.UtilityService.Proxy.Service.ExportJobsResponse EndGetExportJobs(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glyma.UtilityService.Proxy.Service.ExportJobsResponse _result = ((Glyma.UtilityService.Proxy.Service.ExportJobsResponse)(base.EndInvoke("GetExportJobs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetExportJobsForMapType(Glyma.UtilityService.Proxy.Service.MapType mapType, System.Guid domainUid, System.Guid rootMapUid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = mapType;
                _args[1] = domainUid;
                _args[2] = rootMapUid;
                System.IAsyncResult _result = base.BeginInvoke("GetExportJobsForMapType", _args, callback, asyncState);
                return _result;
            }
            
            public Glyma.UtilityService.Proxy.Service.ExportJobsResponse EndGetExportJobsForMapType(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glyma.UtilityService.Proxy.Service.ExportJobsResponse _result = ((Glyma.UtilityService.Proxy.Service.ExportJobsResponse)(base.EndInvoke("GetExportJobsForMapType", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateExportJob(System.Guid domainUid, System.Guid rootMapUid, System.Collections.Generic.Dictionary<string, string> exportProperties, Glyma.UtilityService.Proxy.Service.MapType mapType, Glyma.UtilityService.Proxy.Service.ExportType exportType, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = domainUid;
                _args[1] = rootMapUid;
                _args[2] = exportProperties;
                _args[3] = mapType;
                _args[4] = exportType;
                System.IAsyncResult _result = base.BeginInvoke("CreateExportJob", _args, callback, asyncState);
                return _result;
            }
            
            public Glyma.UtilityService.Proxy.Service.ExportJobResponse EndCreateExportJob(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glyma.UtilityService.Proxy.Service.ExportJobResponse _result = ((Glyma.UtilityService.Proxy.Service.ExportJobResponse)(base.EndInvoke("CreateExportJob", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteExportJob(Glyma.UtilityService.Proxy.Service.ExportJob exportJob, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = exportJob;
                System.IAsyncResult _result = base.BeginInvoke("DeleteExportJob", _args, callback, asyncState);
                return _result;
            }
            
            public Glyma.UtilityService.Proxy.Service.ExportJobResponse EndDeleteExportJob(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glyma.UtilityService.Proxy.Service.ExportJobResponse _result = ((Glyma.UtilityService.Proxy.Service.ExportJobResponse)(base.EndInvoke("DeleteExportJob", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginIsExportingAvailable(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("IsExportingAvailable", _args, callback, asyncState);
                return _result;
            }
            
            public Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse EndIsExportingAvailable(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse _result = ((Glyma.UtilityService.Proxy.Service.ExportAvailabilityResponse)(base.EndInvoke("IsExportingAvailable", _args, result)));
                return _result;
            }
        }
    }
}
