CREATE FULLTEXT CATALOG [FT_Metadata]WITH ACCENT_SENSITIVITY = ON
AUTHORIZATION [dbo]

CREATE FULLTEXT INDEX ON [dbo].[Metadata] KEY INDEX [PK_Metadata] ON ([FT_Metadata]) WITH (CHANGE_TRACKING AUTO)

ALTER FULLTEXT INDEX ON [dbo].[Metadata] ADD ([MetadataValue] LANGUAGE [English])

ALTER FULLTEXT INDEX ON [dbo].[Metadata] ENABLE