GRANT EXECUTE ON OBJECT::dbo.GetChildNodes TO "[ACCOUNT_NAME]";
GRANT EXECUTE ON OBJECT::dbo.GetNodeInMapDetails TO "[ACCOUNT_NAME]";
GRANT EXECUTE ON OBJECT::dbo.GetNodesInMap TO "[ACCOUNT_NAME]";
GRANT EXECUTE ON OBJECT::dbo.GetParentNodes TO "[ACCOUNT_NAME]";
GRANT EXECUTE ON OBJECT::dbo.GetRootMaps TO "[ACCOUNT_NAME]";
