//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glyma.Powershell.Update.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=glyma-dev;Initial Catalog=MappingToolDatabase;Integrated Security=Tru" +
            "e")]
        public string MappingToolDatabaseConnectionString {
            get {
                return ((string)(this["MappingToolDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GLYMA\\SQL2012;Initial Catalog=SP2013_Map_GlymaDB_2;Integrated Securit" +
            "y=True")]
        public string SP2013_Map_GlymaDB_2ConnectionString {
            get {
                return ((string)(this["SP2013_Map_GlymaDB_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GLYMA\\SQL2012;Initial Catalog=SP2013_Map_GlymaDB;Integrated Security=" +
            "True")]
        public string SP2013_Map_GlymaDBConnectionString {
            get {
                return ((string)(this["SP2013_Map_GlymaDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GLYMA2013;Initial Catalog=SP2013_Map_GlymaDB;Integrated Security=True" +
            "")]
        public string SP2013_Map_GlymaDBConnectionString1 {
            get {
                return ((string)(this["SP2013_Map_GlymaDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GLYMA2013;Initial Catalog=Development-Transaction-GlymaDB;Integrated " +
            "Security=True")]
        public string Development_Transaction_GlymaDBConnectionString {
            get {
                return ((string)(this["Development_Transaction_GlymaDBConnectionString"]));
            }
        }
    }
}
